import type { Metadata } from "next";
import localfont from "next/font/local";

import "./globals.css";

const nekst = localfont({
  src: [
    {
      path: "../../public/fonts/Fontspring-DEMO-nekst-light.woff2",
      weight: "300",
    },
    {
      path: "../../public/fonts/Fontspring-DEMO-nekst-regular.woff2",
      weight: "400",
    },
    {
      path: "../../public/fonts/Fontspring-DEMO-nekst-medium.woff2",
      weight: "500",
    },
    {
      path: "../../public/fonts/Fontspring-DEMO-nekst-semibold.woff2",
      weight: "600",
    },
    {
      path: "../../public/fonts/Fontspring-DEMO-nekst-bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-nekst",
});

export const metadata: Metadata = {
  title: "Buyer Lending",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${nekst.variable} max-w-[1440px] mx-auto px-4 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
